### ISSUE TITLE
Wrong link in ES docs

### ISSUE THREAD

**Issue by gian1200** [quarkusio/es.quarkus.io#213]
### Describe the bug

The first link of https://es.quarkus.io/guides/security-cors#references is wrong. It shouldn't have ".adoc" extension in the link

![image](https://github.com/quarkusio/quarkus/assets/405347/0a0f133a-9b38-46a8-83a1-567fa8af9e9d)
![image](https://github.com/quarkusio/quarkus/assets/405347/24f45911-62b7-4d58-920d-bc7aed82d422)

https://es.quarkus.io/guides/security-overview.adoc doesn't exist; but https://es.quarkus.io/guides/security-overview does.

### Expected behavior

Link should redirect to https://es.quarkus.io/guides/security-overview

### Actual behavior

Wrong link redirects to a non existant page (https://es.quarkus.io/guides/security-overview.adoc)

### How to Reproduce?

1. Access to https://es.quarkus.io/guides/security-cors#references
2. Click first link

### Additional information

References list also seems to be outdated in Spanish

**Comment by gsmet** [comment]
I moved the issue to the translation project as I think it's related to the work in this repository.

**Comment by rdnovell** [comment]
Thanks fixed on https://github.com/quarkusio/es.quarkus.io/pull/214
